import { STORAGE_KEY } from '~constants/commands';
import {
  DEFAULT_CHECKED_ALGORITHM_IDS,
  DEFAULT_QUICK_SLOTS_RESPONSE,
  DEFAULT_TOTAMJUNG_THEME,
  DEFAULT_HIDER_OPTIONS,
  DEFAULT_RANDOM_DEFENSE_HISTORY,
  DEFAULT_IS_TIER_HIDDEN,
} from '~constants/defaultValues';

const DEFAULT_INITIAL_DATA = {
  [STORAGE_KEY.CHECKED_ALGORITHM_IDS]: DEFAULT_CHECKED_ALGORITHM_IDS,
  [STORAGE_KEY.QUICK_SLOTS]: DEFAULT_QUICK_SLOTS_RESPONSE,
  [STORAGE_KEY.TOTAMJUNG_THEME]: DEFAULT_TOTAMJUNG_THEME,
  [STORAGE_KEY.HIDER_OPTIONS]: DEFAULT_HIDER_OPTIONS,
  [STORAGE_KEY.RANDOM_DEFENSE_HISTORY]: DEFAULT_RANDOM_DEFENSE_HISTORY,
  [STORAGE_KEY.IS_TIER_HIDDEN]: DEFAULT_IS_TIER_HIDDEN,
  [STORAGE_KEY.DATA_VERSION]: 'v1.2',
};

export const initializeDataOnFirstInstall = () => {
  chrome.storage.local.set(DEFAULT_INITIAL_DATA);
};
